// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pdf} from '../models';

export function CombinePDFs(arg1:Array<pdf.PDFDocument>):Promise<pdf.CombineResult>;

export function CompressPDF(arg1:string,arg2:string):Promise<pdf.CompressionResult>;

export function LoadPDFInfo(arg1:string):Promise<pdf.PDFDocument>;

export function MergeTwoFiles(arg1:string,arg2:string,arg3:string):Promise<pdf.PDFDocument>;

export function OpenFile(arg1:string):Promise<void>;

export function ReorderPages(arg1:string,arg2:Array<number>):Promise<pdf.PDFDocument>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SelectPDFFile():Promise<pdf.FileInfo>;

export function SelectPDFFiles():Promise<Array<pdf.PDFDocument>>;

export function ValidatePDF(arg1:string):Promise<void>;
