// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CombinePDFs(arg1) {
  return window['go']['main']['App']['CombinePDFs'](arg1);
}

export function CompressPDF(arg1, arg2) {
  return window['go']['main']['App']['CompressPDF'](arg1, arg2);
}

export function LoadPDFInfo(arg1) {
  return window['go']['main']['App']['LoadPDFInfo'](arg1);
}

export function MergeTwoFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeTwoFiles'](arg1, arg2, arg3);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function ReorderPages(arg1, arg2) {
  return window['go']['main']['App']['ReorderPages'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SelectPDFFile() {
  return window['go']['main']['App']['SelectPDFFile']();
}

export function SelectPDFFiles() {
  return window['go']['main']['App']['SelectPDFFiles']();
}

export function ValidatePDF(arg1) {
  return window['go']['main']['App']['ValidatePDF'](arg1);
}
